name: Record Release to Airtable

on: 
  push:
    tags: 
      - "*"

jobs:
  record-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install mc-manage package
        run: |
          pip install git+https://github.com/mediacloud/mc-manage@v1.1.5

      - name: Get tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Record successful release
        run: |
          python -m mc-manage.airtable-release-update --name mc-manage --version ${{ env.TAG_NAME }}
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          MEAG_BASE_ID: ${{ secrets.MEAG_BASE_ID}}

